### ISSUE TITLE
Problems specifying ftd2xx as a dependency with install_requires

### ISSUE THREAD

**Issue by kashperanto** [snmishra/ftd2xx#14] opened 2018-05-17 14:28 UTC
As the title says, I am having some issues when I attempt to install ftd2xx by specifying it as a dependency of another package using the install_requires argument to setuptools.setup().  Looking at pip freeze I see that the package is listed as ftd2xx-py3k, even though it exposes itself as ftd2xx when you import it in a python file/repl.

Pip is able to find and install the package just fine when I list ftd2xx as one of the install_requires dependencies , but it shows 'mymodule 0.1 requires ftd2xx, which is not installed'.  Pip appears to expect that your package is installed with the same name it is stored with in PyPI, and for Python 3.X you are appending -py3k and confusing it.

I'm not sure how difficult this would be to fix, but every other package I use works fine with install_requires, so I figure that this is the right place to file the bug.  I assume the -py3k was appended for a reason, but it appears to violate pip's expectations.

**Comment by snmishra** [comment] 2018-05-21 13:19
I think they way we support Python 3 in this library is not a good one. If I were to do it today, I'd rewrite using future library. I can create a new branch, but I don't have a way to test. If @kashperanto , you can test it, I will merge it into master.

**Comment by snmishra** [comment] 2018-05-21 14:53
@kashperanto Please try the py3 branch, URL: https://github.com/snmishra/ftd2xx/archive/py3.zip
I just uploaded some fixes. If this works for you, I'll merge the changes into master.

**Comment by kashperanto** [comment] 2018-05-30 12:59
@snmishra It looks like that works; thanks for the quick response. 👍

I can also do a quick test whenever you merge and update pip in case there is a difference between using the index version and a local folder.

**Comment by awinner1** [comment] 2018-08-06 14:06
any chance of getting this released? I too am running into this issue....

**Comment by snmishra** [comment] 2018-08-06 16:29
Looks I pushed the changes to master some time ago but didn't update this thread. Unfortunately, the current maintainer owns the PyPI listing and has become rather unresponsive. For now, please use the Github URL for installing using pip. I will close the issue, unless something is broken.

**Comment by holdenweb** [comment] 2019-05-13 14:23
I hope I'm not misunderstanding here: the issue is closed but no release has been made since August last year? As you have probably guessed, I am running into the same issue. Downloading from Github really isn't that great a solution. can anything be done, I wonder?

If the present PyPI package owner simply no longer has time or no longer wishes to be involved, a change of maintainer (with everyone's grateful thanks) would be quite easy. I understand there are other paths to change, but I'm not familiar with them.

**Comment by snmishra** [comment] 2019-05-13 18:06
@holdenweb I haven't been able to get a response from @ctrl-shift-esc. Are you saying that PyPI will let me take the repository back?

**Comment by holdenweb** [comment] 2019-05-13 18:34
I don't know the history, or the exact nature of any process to take over a PyPI entry, but if you want to take over maintenance you could also publish a fork under a new name (though I imagine keeping the original would be preferable.

I'd recommend getting in touch with [the packaging WG](https://www.python.org/psf/committees/#packaging-work-group) to discuss the situation with them. If nothing else, they'll know who to contact for an authoritative answer.

**Comment by snmishra** [comment] 2019-05-14 19:30
@holdenweb Thanks for the prompt. I reached out to @ctrl-shift-esc and he has given me ownership of the PyPI project. I intend to update it soon. In the meanwhile, could you confirm that the package in this repo works as it is today? I don't want to replace a broken version with another broken version.

**Comment by holdenweb** [comment] 2019-05-14 19:52
Thatś good news. Glad you can move forward (and many thanks to @ctrl-shift-esc for the original work).

I´m currently using Python 3, and I´ve been having a few issues but now discovered they also occur under 2.7 so I;ll have to get back to you about that, but it´s a current project so it shouldn´t take long. I presume an install from master will work. How about PyPI?

**Comment by snmishra** [comment] 2019-05-14 20:00
@holdenweb The original work was mine. I don't have time to maintain the project, so I had transferred ownership. Now I have it back, but still don't have time to maintain. But I will make any small fixes needed to keep it useful.

Yes, master is the most up to date branch.

**Comment by ctrl-shift-esc** [comment] 2019-05-14 20:32
Hey guys,
The ownership is back in satya's hands. I am no longer associated with this
project.

**Comment by snmishra** [comment] 2019-05-15 21:41
@holdenweb I managed to find a board with an FTDI chip and tested the master branch. I found a few issues and fixed them. Please try the rc at https://pypi.org/project/ftd2xx/1.1.0rc1/ . If it works for you I'll call it 1.1.0

**Comment by holdenweb** [comment] 2019-05-16 14:27
These fixes appear to be satisfactory on my setup too. It would be nice to
have more rigorous testing, but I'm not sure how that could be arranged.
Thanks for persisting with this!

>

**Comment by ctrl-shift-esc** [comment] 2019-05-16 14:50
Hey guys,
As I have given up the ownership of the package, could you please take me
off the mailing list?

Best,
Krishna

**Comment by snmishra** [comment] 2019-05-16 15:14
@ctrl-shift-esc Sorry for the all the traffic you don't want. You are not on any mailing list, but subscribed to this issue because your name was mentioned in one of the comment. I'm going to lock this issue and create a new one to talk about the RC. This should be one of the last emails you get.

**Closed by snmishra** 2019-05-16 15:14 UTC
